ACTIVATE_APPEND = "ResponseActivate"

EVENT_INTERFACE_ACTIVATED = "_E_I_ACTIVATED"
EVENT_INTERFACE_DESTROYED = "_E_I_DESTROYED"
EVENT_INTERFACE_TOP_LEVEL_ELEMENT_CREATED = "_E_I_TOP_LEVEL_CREATED"
EVENT_INTERFACE_GAIN_FOCUS = "_E_I_GAIN_FOCUS"
