

from .paths import *

#fonts
PFENNIG_FONT = "pfennig.ttf"

#images
WHITE_PIXEL_FILENAME = "whitepixel.png"
DEFAULT_INVALID_GRAPHIC = "invalid.png"
DEFAULT_CURSOR_GRAPHIC = "default_cursor.png"

WHITE_PIXEL_FILEPATH = FULL_MISC_PATH + [WHITE_PIXEL_FILENAME]
DEFAULT_INVALID_GRAPHIC_FILEPATH = FULL_MISC_PATH + [DEFAULT_INVALID_GRAPHIC]