


#make sure keybinds keys are strings, not integers, to avoid json problems
CONFIRM = "CONFIRM_BUTTON"
CANCEL = "CANCEL_BUTTON"
MENU = "MENU_BUTTON"
SHOOT = "SHOOT_BUTTON"
PAUSE = "PAUSE_BUTTON"
SELECT = "SELECT_BUTTON"
DEBUG_BUTTON = "DEBUG_BUTTON"
LEFT_MOUSE = "LEFT_MOUSE_BUTTON"
RIGHT_MOUSE = "RIGHT_MOUSE_BUTTON"
MOVE_UP = "MOVE_UP_BUTTON"
MOVE_DOWN = "MOVE_DOWN_BUTTON"
MOVE_RIGHT = "MOVE_RIGHT_BUTTON"
MOVE_LEFT = "MOVE_LEFT_BUTTON"
RIGHT_SHOULDER = "RIGHT_SHOULDER_BUTTON"
LEFT_SHOULDER = "LEFT_SHOULDER_BUTTON"
TAKE_SCREENSHOT = "TAKE_SCREENSHOT_BUTTON"
CAPTURE_ANIMATION = "CAPTURE_ANIMATION_BUTTON"

#not actually bound to anything; just defining names here
