

LAYOUT_FLOW_HORIZONTAL = "horizontal"
LAYOUT_FLOW_VERTICAL = "vertical"

LABEL_JUSTIFICATION_LEFT = "left"
LABEL_JUSTIFICATION_RIGHT = "right"

LAYER_GRAPHICAL_INCREMENT = 1.0
WIDGET_GRAPHICAL_INCREMENT = 0.00001
DEFAULT_CURSOR_LAYER = 10 #reasonably high
