


#resource paths
RESOURCE_PATH = "resources"
LIBRARIES_PATH = "libraries"
SAVES_PATH = "saves"
GRAPHICS_PATH = "graphics"
CODE_PATH = "code"
AUDIO_PATH = "audio"
STRINGS_PATH = "strings"

#code resources folders
GRAPHIC_OBJECTS_DIR = "graphicobjects"

#graphics resource folders
FONT_DIR = "fonts"
SPRITE_DIR = "sprites"
GRAPHIC_MISC_DIR = "misc"

#audio resource folders
MUSIC_DIR = "music"
SFX_DIR = "fx"


#misc
MISC_DIR = "misc"
SETTINGS_FILE_NAME = "options"
ARCHIVE_FILE_NAME = "resources.dat"
TEXT_DIR = "text" #deprecated; used only in DoL
WIDGET_PATH = "widgets"
LOG_PATH = "logs"
LOG_FILENAME_HEADER = "log"

#full paths
FULL_FONT_PATH = [RESOURCE_PATH, GRAPHICS_PATH, FONT_DIR]
FULL_STRINGS_PATH = [RESOURCE_PATH, STRINGS_PATH]
FULL_SPRITE_PATH = [RESOURCE_PATH, GRAPHICS_PATH, SPRITE_DIR]
FULL_GRAPHIC_OBJECTS_PATH = [RESOURCE_PATH, CODE_PATH, GRAPHIC_OBJECTS_DIR]
FULL_MISC_PATH = [RESOURCE_PATH, MISC_DIR]
FULL_GRAPHIC_MISC_PATH = [RESOURCE_PATH, GRAPHICS_PATH, GRAPHIC_MISC_DIR]
FULL_MUSIC_PATH = [RESOURCE_PATH, AUDIO_PATH, MUSIC_DIR]
FULL_SFX_PATH = [RESOURCE_PATH, AUDIO_PATH, SFX_DIR]
#note: save path in settingskeys.py, or overwritten in local dynamic settings

#extensions
PNG_EXTENSION = ".png"
ANI_EXTENSION = ".ani"
TTF_EXTENSION = ".ttf"
PYTHON_EXTENSION = ".py"
TEXT_EXTENSION = ".txt"
STRINGS_EXTENSION = ".strings"
STRINGS_METADATA_EXTENSION = ".stringsmeta"
GRAPHIC_FONT_EXTENSION = ".gfont"
GRAPHIC_FONT_2_EXTENSION = ".gfont2"
GRAPHIC_FONT_3_EXTENSION = ".gfont3"
GRAPHIC_OBJECT_EXTENSION = ".gfxobj"
IMAGE_EXTENSION = PNG_EXTENSION
LABEL_OBJECT_EXTENSION = ".label"
BORDERED_SPRITE_EXTENSION = ".bordered"
MULTI_SPRITE_EXTENSION = ".multi"
CONFIG_EXTENSION = ".config"
SAVE_EXTENSION = ".sav"
SOUND_EXTENSION = ".ogg"
LOG_EXTENSION = ".log"


#strings filenames
STRINGS_META_FILENAME = "_metadata" + STRINGS_METADATA_EXTENSION
STRINGS_MISC_FILENAME = "misc" + STRINGS_EXTENSION

