# -*- coding: utf-8 -*-

CONFIRM_KEY = "confirm"
CANCEL_KEY = "cancel"
MOVEUP_KEY = "moveup"
MOVEDOWN_KEY = "movedown"
MOVERIGHT_KEY = "moveright"
MOVELEFT_KEY = "moveleft"
MOUSEENTER_KEY = "mouseenter"
MOUSEOVER_KEY = "moouseover"
MOUSELEAVE_KEY = "mouseleave"
GAINFOCUS_KEY = "gainfocus"
LOSEFOCUS_KEY = "losefocus"

BASIC_EVENT_KEYS = (CONFIRM_KEY, CANCEL_KEY, MOVEUP_KEY, MOVEDOWN_KEY, MOVERIGHT_KEY, MOVELEFT_KEY, MOUSEENTER_KEY, MOUSEOVER_KEY, MOUSELEAVE_KEY, GAINFOCUS_KEY, LOSEFOCUS_KEY)